### PR TITLE
Mute and Volume options

### PR DESCRIPTION
**Pull request by XanC**
I had a need for the video to start muted, so that it would autoplay.  Might as well be able to set the volume too.

### CODE REVIEW

**Comment by henrygd** [comment]
Good idea on the volume option.  Are you sure we need a `muted` attribute to allow autoplay? I tested in chrome and setting volume to 0 allows autoplay without the attribute. Maybe safari or phones need it?

Also, I'm not understanding what's going on with 92ad056. Seems to revert 7c4ed7e. Do you not want 7c4ed7e changes merged?

**Comment by XanC** [comment]
Hello Hank,

Thanks for looking into my suggestions, and for BigPicture in general!

Apologies about the reversion.  I am a complete newbie when it comes to 
git.  I've made just a handful of pull requests over the years for 
various projects, and I think this was the first time that I've had 
multiple different requests for a single project.

Basically I mishandled the whole forking/branches/commit process.  My 
two pull requests should have nothing to do with each other.  I think 
both are helpful but they're entirely independent.  I just messed up 
trying to achieve that.

On the muted attribute: I don't think "mute" and "volume 0" are /quite/ 
the same.  I can set the volume to, say, 75% and set "mute", then when 
the user unmutes the initial volume level is what I've set.

**Comment by henrygd** [comment]
No worries, I appreciate the contribution. Sorry it's taking so long to get back to you.

Out of curiosity, which device / browser are you using where autoplay doesn't work? I've tested the demo site with windows, macos, android, and ios, and it works without being muted, because it's being opened in response to a click event.

The other pull request it's breaking the build command so I need to figure out what's happening before merging anything.

**Comment by XanC** [comment]
Firefox on Linux is where I've observed the issue.  But it's only when I'm loading a BigPicture video on page load rather than as the result of a click.

**Comment by henrygd** [comment]
Would you mind pulling a fresh copy and adding these changes with a new pull request? It's just a bit messy with the extra commits that were backed out and there being another commit to main after this pr.

**Pull request closed without merging**
